version: '3.9'

networks:
  nwt_network:
    external: true

services:
  eureka-server:
    image: "eureka-server"
    container_name: eureka-server
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./EurekaServer
    networks:
      - nwt_network
    ports:
      - "8761:8761"

  config-server:
    image: "config-server"
    container_name: config-server
    restart: on-failure
    networks:
      - nwt_network
    build:
      dockerfile: Dockerfile
      context: ./ConfigServer
    ports:
      - "8888:8888"

  api-gateway:
    image: "api-gateway"
    container_name: api-gateway
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./api_gateway
    depends_on:
      - eureka-server
      - config-server
    environment:
      - CONFIG_SERVER_URL=http://admin:nimda@config-server:8888
      - EUREKA_DEFAULT_ZONE=http://eureka-server:8761/eureka/
      - REQUEST_SERVICE_URI=lb://REQUEST-SERVICE
      - ROOM_SERVICE_URI=lb://ROOM-SERVICE
      - PERMISSION_SERVICE_URI=lb://PERMISSION-SERVICE
    ports:
      - "8080:8080"
    networks:
      - nwt_network

  system-events:
    image: "system-events"
    container_name: system-events
    restart: on-failure
    networks:
      - nwt_network
    build:
      dockerfile: Dockerfile
      context: ./system_events
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql-fra1-62529-do-user-16093561-0.c.db.ondigitalocean.com:25060/System_Events?sslMode=REQUIRED
      - SPRING_DATASOURCE_USERNAME=doadmin
      - SPRING_DATASOURCE_PASSWORD=AVNS_25qDqGi9EyQX21DDfeH
      - CONFIG_SERVER_URL=http://admin:nimda@config-server:8888
    ports:
      - "6565:6565"

  request-service:
    image: "request-service"
    container_name: request-service
    restart: on-failure
    networks:
      - nwt_network
    build:
      dockerfile: Dockerfile
      context: ./RequestService
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql-fra1-62529-do-user-16093561-0.c.db.ondigitalocean.com:25060/RequestServiceDB?sslMode=REQUIRED
      - SPRING_DATASOURCE_USERNAME=doadmin
      - SPRING_DATASOURCE_PASSWORD=AVNS_25qDqGi9EyQX21DDfeH
      - CONFIG_SERVER_URL=http://admin:nimda@config-server:8888
      - EUREKA_DEFAULT_ZONE=http://eureka-server:8761/eureka/

  room-service:
    image: "room-service"
    container_name: room-service
    restart: on-failure
    networks:
      - nwt_network
    build:
      dockerfile: Dockerfile
      context: ./RoomService
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql-fra1-62529-do-user-16093561-0.c.db.ondigitalocean.com:25060/RoomServiceDB?sslMode=REQUIRED
      - SPRING_DATASOURCE_USERNAME=doadmin
      - SPRING_DATASOURCE_PASSWORD=AVNS_25qDqGi9EyQX21DDfeH
      - CONFIG_SERVER_URL=http://admin:nimda@config-server:8888
      - EUREKA_DEFAULT_ZONE=http://eureka-server:8761/eureka/


  permission-service:
    image: "permission-service"
    container_name: permission-service
    restart: on-failure
    networks:
      - nwt_network
    build:
      dockerfile: Dockerfile
      context: ./PermissionService
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql-fra1-62529-do-user-16093561-0.c.db.ondigitalocean.com:25060/PermissionServiceDB?sslMode=REQUIRED
      - SPRING_DATASOURCE_USERNAME=doadmin
      - SPRING_DATASOURCE_PASSWORD=AVNS_25qDqGi9EyQX21DDfeH
      - CONFIG_SERVER_URL=http://admin:nimda@config-server:8888
      - EUREKA_DEFAULT_ZONE=http://eureka-server:8761/eureka/


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - nwt_network
    ports:
      - "5672:5672"
      - "15672:15672"

