
networks:
  nwt_network:
    external: true
    driver: bridge

services:
  eureka-server:
    container_name: eureka-server
    image: "eureka-server"
    build:
      context: ./EurekaServer
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - nwt_network
    ports:
      - "8761:8761"

  config-server:
    container_name: config-server
    image: "config-server"
    build:
      context: ./ConfigServer
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      CONFIG_SERVER_GIT_PASSWORD: ${CONFIG_SERVER_GIT_PASSWORD}
    networks:
      - nwt_network
    ports:
      - "8888:8888"

  api-gateway:
    container_name: api-gateway
    image: "api-gateway"
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - eureka-server
      - config-server
    environment:
      - CONFIG_SERVER_URL=http://admin:nimda@config-server:8888
      - EUREKA_DEFAULT_ZONE=http://eureka-server:8761/eureka/
      - GRPC_SERVER_ADDRESS=system-events
      - GRPC_SERVER_PORT=6565
    ports:
      - "8080:8080"
    networks:
      - nwt_network

  system-events:
    container_name: system-events
    image: "system-events"
    build:
      context: ./system_events
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - eureka-server
      - api-gateway
      - system-events-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://system-events-db:3306/SystemEventsDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    ports:
      - "6565:6565"
    networks:
      - nwt_network

  request-service:
    container_name: request-service
    image: "request-service"
    build:
      context: ./RequestService
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
      - request-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://request-db:3306/RequestServiceDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - CONFIG_SERVER_URL=http://admin:nimda@config-server:8888
      - EUREKA_DEFAULT_ZONE=http://eureka-server:8761/eureka/
    networks:
      - nwt_network

  room-service:
    container_name: room-service
    image: "room-service"
    build:
      context: ./RoomService
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
      - room-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://room-db:3306/RoomServiceDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - CONFIG_SERVER_URL=http://admin:nimda@config-server:8888
      - EUREKA_DEFAULT_ZONE=http://eureka-server:8761/eureka/
    networks:
      - nwt_network

  permission-service:
    container_name: permission-service
    image: "permission-service"
    build:
      context: ./PermissionService
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
      - permission-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://permission-db:3306/PermissionServiceDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - CONFIG_SERVER_URL=http://admin:nimda@config-server:8888
      - EUREKA_DEFAULT_ZONE=http://eureka-server:8761/eureka/
    networks:
      - nwt_network

  request-db:
    container_name: request-db
    image: mysql:5.7
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=RequestServiceDB
    networks:
      - nwt_network
    ports:
      - "33066:3306"

  room-db:
    container_name: room-db
    image: mysql:5.7
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=RoomServiceDB
    networks:
      - nwt_network
    ports:
      - "33067:3306"

  permission-db:
    container_name: permission-db
    image: mysql:5.7
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=PermissionServiceDB
    networks:
      - nwt_network
    ports:
      - "33068:3306"

  system-events-db:
    container_name: system-events-db
    image: mysql:5.7
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=SystemEventsDB
    networks:
      - nwt_network
    ports:
      - "33069:3306"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - nwt_network
    ports:
      - "5672:5672"
      - "15672:15672"

  frontend:
    image: frontend:latest
    container_name: frontend
    build:
      context: ./NWT-FE
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - './NWT-FE:/app'
      - '/app/node_modules'
    networks:
      - nwt_network
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=http://localhost:8080
