server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: requestService
          uri: lb://REQUESTSERVICE # Replace with the name of the service registered in Eureka
          predicates:
            - Path=/user/**
        - id: roomService
          uri: lb://ROOMSERVICE # Replace with the name of the service registered in Eureka
          predicates:
            - Path=/room/**
        - id: permissionService
          uri: lb://PERMISSIONSERVICE # Replace with the name of the service registered in Eureka
          predicates:
            - Path=/api/**

