# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_events.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13system_events.proto\x12\x0csystemevents\"{\n\x13SystemEventsRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x14\n\x0cmicroservice\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\x12\x10\n\x08resource\x18\x05 \x01(\t\x12\x10\n\x08response\x18\x06 \x01(\t\"&\n\x14SystemEventsResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2j\n\x0cSystemEvents\x12Z\n\x0fGetSystemEvents\x12!.systemevents.SystemEventsRequest\x1a\".systemevents.SystemEventsResponse\"\x00\x42\x30\n\x19\x63om.example.system_eventsB\x11SystemEventsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.example.system_eventsB\021SystemEventsProtoP\001'
  _globals['_SYSTEMEVENTSREQUEST']._serialized_start=37
  _globals['_SYSTEMEVENTSREQUEST']._serialized_end=160
  _globals['_SYSTEMEVENTSRESPONSE']._serialized_start=162
  _globals['_SYSTEMEVENTSRESPONSE']._serialized_end=200
  _globals['_SYSTEMEVENTS']._serialized_start=202
  _globals['_SYSTEMEVENTS']._serialized_end=308
# @@protoc_insertion_point(module_scope)
